"""add Department

Revision ID: 640606b11081
Revises: fa4400ae7fb1
Create Date: 2024-07-04 18:40:21.199220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640606b11081'
down_revision = 'fa4400ae7fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
